version: "3.5"
services:
  app:
    env_file: ./Docker/.env
    build:
      context: ./Docker/app
    networks:
      - portfolio
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./:/usr/share/nginx/html
  varnish:
    env_file: ./Docker/.env
    build: 
      context: ./Docker/varnish
    depends_on: 
      - app
    ports:
      - "127.0.0.1:8080:6081"
    networks:
      - portfolio
  gulp:
    env_file: ./Docker/.env
    build: 
      context: ./Docker/gulp
    volumes:
      - ./css:/css
      - ./js:/js
      - ./scss:/scss
      - ./package.json:/build/package.json
      - ./gulpfile.js:/build/gulpfile.js
      - ./vendor:/vendor-assets
#  test:
#    env_file: ./Docker/.env
#    build: 
#      context: ./Docker/test
#    depends_on:
#      - app
#      - varnish
#    ports:
#      - "127.0.0.1:8082:80"
#    networks:
#      - portfolio
networks:
  portfolio:
    name: portfolio
  default:
    name: portfolio
