---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: portfolio
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "portfolio.k8s.rubyninja.org"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portfolio
spec:
  hosts:
  - "portfolio.k8s.rubyninja.org"
  gateways:
  - portfolio
  http:
  - route:
    - destination:
        host: portfolio
        port:
          number: 6081
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
    service: portfolio
spec:
  ports:
  - port: 6081
    name: http
  selector:
    app: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio
  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - env:
            - name: APP_ENV
              value: prod
            - name: APP_HOST
              value: 127.0.0.1
          name: varnish
          image: alpha01jenkins/portfolio_varnish:${trigger.tag}
          ports:
            - containerPort: 6081
        - name: app
          image: alpha01jenkins/portfolio_app:${trigger.tag}
          ports:
            - containerPort: 80
