# docker-compose file used by check_site 
version: "3.5"
services:
  app:
    image: alpha01jenkins/portfolio_app:##TAG##
    networks:
      - portfolio
  varnish:
    env_file: ../Docker/.env
    image: alpha01jenkins/portfolio_varnish:##TAG##
    depends_on: 
      - app
    ports:
      - "6081"
    networks:
      - portfolio
networks:
  portfolio:
    name: portfolio
  default:
    name: portfolio
